# Generated by Django 5.2.15 on 2026-06-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_of_transfer',
            field=models.ImageField(blank=True, help_text='Bukti transfer (JPG/PNG, max 70KB)', null=True, upload_to='payments/proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='selected_bank',
            field=models.CharField(blank=True, choices=[('BCA', 'Bank Central Asia (BCA)'), ('BNI', 'Bank Negara Indonesia (BNI)'), ('BRI', 'Bank Rakyat Indonesia (BRI)'), ('MANDIRI', 'Bank Mandiri'), ('BSI', 'Bank Syariah Indonesia (BSI)')], help_text='Bank yang dipilih user untuk transfer', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Transfer Bank Manual')], default='BANK_TRANSFER', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='response_payload',
            field=models.JSONField(blank=True, help_text='Payload response dari payment gateway', null=True),
        ),
    ]
