# Generated by Django 5.2.15 on 2026-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_proof_of_transfer_payment_selected_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='destination_account_name',
            field=models.CharField(blank=True, help_text='Nama pemilik rekening tujuan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='destination_account_number',
            field=models.CharField(blank=True, help_text='Nomor rekening tujuan transfer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='selected_bank',
            field=models.CharField(blank=True, choices=[('BCA', 'Bank Central Asia (BCA)'), ('BNI', 'Bank Negara Indonesia (BNI)'), ('BRI', 'Bank Rakyat Indonesia (BRI)'), ('MANDIRI', 'Bank Mandiri'), ('CIMB', 'CIMB Niaga'), ('BSI', 'Bank Syariah Indonesia (BSI)')], help_text='Bank yang dipilih user untuk transfer', max_length=20, null=True),
        ),
    ]
