# Generated by Django 5.2.15 on 2026-06-13 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Voucher code, e.g. ELEKTRO2026', max_length=50, unique=True)),
                ('discount_percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maksimal nominal diskon', max_digits=12, null=True)),
                ('min_spend', models.DecimalField(decimal_places=2, default=0, help_text='Minimum belanja', max_digits=12)),
                ('expiry_date', models.DateField()),
                ('active_limit', models.PositiveIntegerField(blank=True, help_text='Maksimal total penggunaan voucher', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
