# Generated by Django 5.2.15 on 2026-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='unique_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('AWAITING_VERIFICATION', 'Menunggu Verifikasi'), ('PAID', 'Lunas'), ('PROCESSING', 'Diproses'), ('SHIPPED', 'Dikirim'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=30),
        ),
    ]
