# Generated by Django 5.2.15 on 2026-06-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_shipping_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='service',
            field=models.CharField(blank=True, default='REG', help_text='Paket layanan: REG, YES, OKE, ONS, ECO, BIASA, KILAT', max_length=20),
        ),
    ]
