# Generated by Django 5.2.15 on 2026-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_shipment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='courier',
            field=models.CharField(choices=[('JNE', 'JNE'), ('JNT', 'J&T Express'), ('SICEPAT', 'SiCepat'), ('POS', 'POS Indonesia'), ('TIKI', 'TIKI')], default='JNE', max_length=10),
        ),
    ]
